### ISSUE TITLE
Anchor tag to other page not working as expected

### ISSUE THREAD

**Issue by jrson83** [nanojsx/nanojsx.github.io#14]
I just noticed, if you define an anchor link to another page with code boxes, the link does not work as expected. The code boxes take some time to load and you don't land at the proper anchor position. I will create another PR and remove the anchor link.
Maybe in future it is possible to add an async scroll behaviour for this, but I'm not sure if this is needed/worth.

**Comment by yandeu** [comment]
Or pre-render the boxes.
